const express = require('express');
const cors = require('cors');
const fs = require('fs');
const path = require('path');
const { exec } = require('child_process');
const util = require('util');
const { registerProcessRoutes } = require('./routes');
const { registerManagementRoutes } = require('./managementRoutes');
const { registerAnalysisRoutes } = require('./analysisRoutes');
const { registerProjectCreationRoutes } = require('./projectCreationRoutes');
const { registerTodoAiRoutes } = require('./todoAiRoutes');
const fileRoutes = require('./fileRoutes');
const processManager = require('./processManager');
const db = require('./database');
require('dotenv').config({ path: path.resolve(__dirname, '../.env') });

const execPromise = util.promisify(exec);

const app = express();
const PORT = process.env.PORT || 9999;

// 项目根目录配置
// 优先使用环境变量配置的绝对路径，避免相对路径问题
// 如果未配置，默认使用 backend 的上两级目录（../.. = Project 目录）
const PROJECT_ROOT = process.env.PROJECT_ROOT
  ? path.resolve(process.env.PROJECT_ROOT)
  : path.resolve(__dirname, '../..');
const PROJECTS_CONFIG = path.join(PROJECT_ROOT, '.claude/projects.json');
const ENV_FILE = path.resolve(__dirname, '../.env');

app.use(cors());
app.use(express.json());

// 提供前端静态文件
app.use(express.static(path.join(__dirname, '../frontend/dist')));

// ========== API 路由 ==========

// 配置管理API
// 获取配置
app.get('/api/config', (req, res) => {
  try {
    const config = {
      ANTHROPIC_API_KEY: process.env.ANTHROPIC_API_KEY || '',
      ANTHROPIC_BASE_URL: process.env.ANTHROPIC_BASE_URL || 'https://api.husanai.com',
      OPENAI_API_KEY: process.env.OPENAI_API_KEY || '',
      OPENAI_BASE_URL: process.env.OPENAI_BASE_URL || 'https://api.openai.com',
      DEFAULT_AI_ENGINE: process.env.DEFAULT_AI_ENGINE || 'claude-code',
      PROJECT_ROOT: process.env.PROJECT_ROOT || ''
    };
    res.json(config);
  } catch (error) {
    res.status(500).json({ error: '读取配置失败', message: error.message });
  }
});

// 保存配置
app.post('/api/config', (req, res) => {
  try {
    const { ANTHROPIC_API_KEY, ANTHROPIC_BASE_URL, OPENAI_API_KEY, OPENAI_BASE_URL, DEFAULT_AI_ENGINE, PROJECT_ROOT } = req.body;

    // 读取现有的 .env 文件或创建新的
    let envContent = '';
    if (fs.existsSync(ENV_FILE)) {
      envContent = fs.readFileSync(ENV_FILE, 'utf8');
    }

    // 解析现有配置
    const envLines = envContent.split('\n');
    const envMap = new Map();
    const comments = [];

    envLines.forEach(line => {
      if (line.trim().startsWith('#') || line.trim() === '') {
        comments.push(line);
      } else if (line.includes('=')) {
        const [key, ...valueParts] = line.split('=');
        envMap.set(key.trim(), valueParts.join('=').trim());
      }
    });

    // 更新配置
    if (ANTHROPIC_API_KEY !== undefined) {
      envMap.set('ANTHROPIC_API_KEY', ANTHROPIC_API_KEY);
    }
    if (ANTHROPIC_BASE_URL !== undefined) {
      envMap.set('ANTHROPIC_BASE_URL', ANTHROPIC_BASE_URL);
    }
    if (OPENAI_API_KEY !== undefined) {
      envMap.set('OPENAI_API_KEY', OPENAI_API_KEY);
    }
    if (OPENAI_BASE_URL !== undefined) {
      envMap.set('OPENAI_BASE_URL', OPENAI_BASE_URL);
    }
    if (DEFAULT_AI_ENGINE !== undefined) {
      envMap.set('DEFAULT_AI_ENGINE', DEFAULT_AI_ENGINE);
    }
    if (PROJECT_ROOT !== undefined) {
      envMap.set('PROJECT_ROOT', PROJECT_ROOT);
    }

    // 生成新的 .env 内容
    const newEnvContent = [
      '# Environment Configuration',
      '# Generated by Claude Code Project Manager',
      '',
      '# Claude API Configuration',
      `ANTHROPIC_API_KEY=${envMap.get('ANTHROPIC_API_KEY') || ''}`,
      `ANTHROPIC_BASE_URL=${envMap.get('ANTHROPIC_BASE_URL') || 'https://api.husanai.com'}`,
      '',
      '# OpenAI API Configuration',
      `OPENAI_API_KEY=${envMap.get('OPENAI_API_KEY') || ''}`,
      `OPENAI_BASE_URL=${envMap.get('OPENAI_BASE_URL') || 'https://api.openai.com'}`,
      '',
      '# Default AI Engine',
      `DEFAULT_AI_ENGINE=${envMap.get('DEFAULT_AI_ENGINE') || 'claude-code'}`,
      '',
      '# Server Configuration',
      `PORT=${envMap.get('PORT') || '9999'}`,
      '',
      '# Project Root',
      `PROJECT_ROOT=${envMap.get('PROJECT_ROOT') || ''}`,
      ''
    ].join('\n');

    fs.writeFileSync(ENV_FILE, newEnvContent, 'utf8');

    // 更新环境变量
    process.env.ANTHROPIC_API_KEY = envMap.get('ANTHROPIC_API_KEY') || '';
    process.env.ANTHROPIC_BASE_URL = envMap.get('ANTHROPIC_BASE_URL') || 'https://api.husanai.com';
    process.env.OPENAI_API_KEY = envMap.get('OPENAI_API_KEY') || '';
    process.env.OPENAI_BASE_URL = envMap.get('OPENAI_BASE_URL') || 'https://api.openai.com';
    process.env.DEFAULT_AI_ENGINE = envMap.get('DEFAULT_AI_ENGINE') || 'claude-code';
    process.env.PROJECT_ROOT = envMap.get('PROJECT_ROOT') || '';

    res.json({ success: true, message: '配置保存成功' });
  } catch (error) {
    res.status(500).json({ error: '保存配置失败', message: error.message });
  }
});

// 1. 获取所有项目
app.get('/api/projects', (req, res) => {
  try {
    const config = db.getProjectsForConfig();
    res.json(config);
  } catch (error) {
    res.status(500).json({ error: '读取项目配置失败', message: error.message });
  }
});

// 2. 获取单个项目状态
app.get('/api/projects/:name/status', async (req, res) => {
  try {
    const { name } = req.params;
    const project = db.getProjectByName(name);

    if (!project) {
      return res.status(404).json({ error: '项目不存在' });
    }

    // 转换数据库格式到前端格式
    const projectData = {
      path: project.path,
      description: project.description,
      status: project.status,
      port: project.port,
      stack: project.tech ? JSON.parse(project.tech) : [],
      startCommand: project.start_command
    };

    // 如果是绝对路径直接使用，否则相对于项目根目录
    const projectPath = path.isAbsolute(project.path)
      ? project.path
      : path.join(PROJECT_ROOT, project.path);
    const status = await checkProjectStatus(projectPath, projectData);

    res.json({ name, ...status });
  } catch (error) {
    res.status(500).json({ error: '检查项目状态失败', message: error.message });
  }
});

// 3. 批量获取项目状态
app.post('/api/projects/status/batch', async (req, res) => {
  try {
    const { projectNames } = req.body;

    const statusPromises = projectNames.map(async (name) => {
      const project = db.getProjectByName(name);

      if (!project) return { name, error: '项目不存在' };

      // 转换数据库格式
      const projectData = {
        path: project.path,
        description: project.description,
        status: project.status,
        port: project.port,
        stack: project.tech ? JSON.parse(project.tech) : [],
        startCommand: project.start_command
      };

      // 如果是绝对路径直接使用，否则相对于项目根目录
      const projectPath = path.isAbsolute(project.path)
        ? project.path
        : path.join(PROJECT_ROOT, project.path);
      const status = await checkProjectStatus(projectPath, projectData);
      return { name, ...status };
    });

    const results = await Promise.all(statusPromises);
    res.json(results);
  } catch (error) {
    res.status(500).json({ error: '批量检查失败', message: error.message });
  }
});

// 4. 更新项目配置（已废弃 - 请使用 PUT /api/projects/:name）
app.put('/api/projects', (req, res) => {
  res.status(410).json({
    error: '此端点已废弃',
    message: '请使用 PUT /api/projects/:name 更新单个项目',
    deprecated: true
  });
});

// 5. 执行项目操作
app.post('/api/projects/:name/action', async (req, res) => {
  try {
    const { name } = req.params;
    const { action, params } = req.body;

    const project = db.getProjectByName(name);

    if (!project) {
      return res.status(404).json({ error: '项目不存在' });
    }

    // 转换数据库格式
    const projectData = {
      path: project.path,
      description: project.description,
      status: project.status,
      port: project.port,
      stack: project.tech ? JSON.parse(project.tech) : [],
      startCommand: project.start_command
    };

    // 如果是绝对路径直接使用，否则相对于项目根目录
    const projectPath = path.isAbsolute(project.path)
      ? project.path
      : path.join(PROJECT_ROOT, project.path);
    const result = await executeAction(action, projectPath, projectData, params);

    res.json(result);
  } catch (error) {
    res.status(500).json({ error: '执行操作失败', message: error.message });
  }
});

// ========== 辅助函数 ==========

// 检查项目状态
async function checkProjectStatus(projectPath, project) {
  const status = {
    exists: fs.existsSync(projectPath),
    hasGit: false,
    gitBranch: null,
    uncommittedFiles: 0,
    hasDependencies: false,
    dependenciesInstalled: false,
    port: project.port || null
  };

  if (!status.exists) return status;

  // 检查 Git 状态
  const gitPath = path.join(projectPath, '.git');
  status.hasGit = fs.existsSync(gitPath);

  if (status.hasGit) {
    try {
      const { stdout: branch } = await execPromise('git branch --show-current', { cwd: projectPath });
      status.gitBranch = branch.trim();

      const { stdout: statusOutput } = await execPromise('git status --porcelain', { cwd: projectPath });
      status.uncommittedFiles = statusOutput.trim().split('\n').filter(l => l).length;
    } catch (error) {
      // Git 命令失败，忽略
    }
  }

  // 检查依赖状态
  const hasPackageJson = fs.existsSync(path.join(projectPath, 'package.json'));
  const hasRequirements = fs.existsSync(path.join(projectPath, 'requirements.txt')) ||
                          fs.existsSync(path.join(projectPath, 'backend/requirements.txt'));

  status.hasDependencies = hasPackageJson || hasRequirements;

  if (hasPackageJson) {
    status.dependenciesInstalled = fs.existsSync(path.join(projectPath, 'node_modules'));
  } else if (hasRequirements) {
    status.dependenciesInstalled = fs.existsSync(path.join(projectPath, 'venv')) ||
                                   fs.existsSync(path.join(projectPath, '.venv')) ||
                                   fs.existsSync(path.join(projectPath, 'backend/venv'));
  }

  return status;
}

// 执行操作
async function executeAction(action, projectPath, project, params) {
  switch (action) {
    case 'open-directory':
      await execPromise(`open "${projectPath}"`);
      return { success: true, message: '已打开项目目录' };

    case 'open-vscode':
      await execPromise(`code "${projectPath}"`);
      return { success: true, message: '已在 VSCode 中打开' };

    case 'git-status':
      const { stdout } = await execPromise('git status', { cwd: projectPath });
      return { success: true, output: stdout };

    case 'install-deps':
      if (fs.existsSync(path.join(projectPath, 'package.json'))) {
        await execPromise('npm install', { cwd: projectPath });
        return { success: true, message: 'npm 依赖安装完成' };
      } else if (fs.existsSync(path.join(projectPath, 'requirements.txt'))) {
        await execPromise('pip install -r requirements.txt', { cwd: projectPath });
        return { success: true, message: 'Python 依赖安装完成' };
      }
      return { success: false, message: '未找到依赖配置文件' };

    default:
      return { success: false, message: '未知操作' };
  }
}

// ========== 项目创建 API（必须在 CRUD 之前） ==========

// 注册项目创建路由（AI 一句话创建项目）
// ⚠️ 重要：必须在 /api/projects/:name 之前注册，避免路由冲突
registerProjectCreationRoutes(app, PROJECT_ROOT);

// ========== 项目 CRUD API ==========

// 添加新项目
app.post('/api/projects/:name', async (req, res) => {
  try {
    const { name } = req.params;
    const { project, isExternal } = req.body;

    // 验证参数
    if (!project) {
      console.error('[ProjectAPI] 添加项目失败: project 参数为 undefined');
      console.error('[ProjectAPI] 请求体:', JSON.stringify(req.body, null, 2));
      return res.status(400).json({ error: '缺少 project 参数' });
    }
    if (!project.path || !project.path.trim()) {
      console.error('[ProjectAPI] 添加项目失败: project.path 为空');
      console.error('[ProjectAPI] project:', JSON.stringify(project, null, 2));
      return res.status(400).json({ error: '项目路径不能为空' });
    }

    // 检查项目是否已存在
    const existing = db.getProjectByName(name);
    if (existing) {
      return res.status(400).json({ error: '项目名称已存在' });
    }

    // 添加到数据库
    db.addProject(name, project, isExternal);

    // 自动触发项目分析（异步）
    const projectPath = isExternal ? project.path : path.join(PROJECT_ROOT, project.path);
    if (fs.existsSync(projectPath)) {
      setImmediate(async () => {
        try {
          console.log(`[ProjectCRUD] 自动分析新项目: ${name}`);
          db.updateProjectAnalysisStatus(name, 'analyzing');
          const projectAnalyzer = require('./projectAnalyzer');
          const analysis = await projectAnalyzer.analyzeProject(name, projectPath);
          db.saveProjectAnalysis(name, analysis);
          console.log(`[ProjectCRUD] ✅ 项目分析完成: ${name}`);
        } catch (error) {
          console.error(`[ProjectCRUD] ❌ 项目分析失败: ${name}`, error);
          db.updateProjectAnalysisStatus(name, 'failed', error.message);
        }
      });
    }

    res.json({ success: true, message: '项目添加成功' });
  } catch (error) {
    res.status(500).json({ error: '添加项目失败', message: error.message });
  }
});

// 更新项目
app.put('/api/projects/:name', async (req, res) => {
  try {
    const { name } = req.params;
    const { project, isExternal } = req.body;

    // 检查项目是否存在
    const existing = db.getProjectByName(name);
    if (!existing) {
      return res.status(404).json({ error: '项目不存在' });
    }

    // 更新数据库
    db.updateProject(name, project, isExternal);

    res.json({ success: true, message: '项目更新成功' });
  } catch (error) {
    res.status(500).json({ error: '更新项目失败', message: error.message });
  }
});

// 删除项目
app.delete('/api/projects/:name', (req, res) => {
  try {
    const { name } = req.params;

    // 检查项目是否存在
    const existing = db.getProjectByName(name);
    if (!existing) {
      return res.status(404).json({ error: '项目不存在' });
    }

    // 从数据库删除
    db.deleteProject(name);

    res.json({ success: true, message: '项目删除成功' });
  } catch (error) {
    res.status(500).json({ error: '删除项目失败', message: error.message });
  }
});

// 打开文件夹选择对话框并自动识别项目信息
app.post('/api/select-folder', async (req, res) => {
  try {
    // 使用 osascript (macOS) 或其他系统命令打开文件夹选择器
    const platform = process.platform;
    let folderPath = '';

    if (platform === 'darwin') {
      // macOS - 使用 AppleScript
      const { stdout } = await execPromise(
        'osascript -e \'POSIX path of (choose folder with prompt "选择项目文件夹")\''
      );
      folderPath = stdout.trim();
    } else if (platform === 'win32') {
      // Windows - 使用 PowerShell
      const psScript = `
        Add-Type -AssemblyName System.Windows.Forms
        $dialog = New-Object System.Windows.Forms.FolderBrowserDialog
        $dialog.Description = "选择项目文件夹"
        $result = $dialog.ShowDialog()
        if ($result -eq 'OK') { Write-Output $dialog.SelectedPath }
      `;
      const { stdout } = await execPromise(`powershell -Command "${psScript}"`);
      folderPath = stdout.trim();
    } else {
      // Linux - 尝试使用 zenity
      const { stdout } = await execPromise('zenity --file-selection --directory --title="选择项目文件夹"');
      folderPath = stdout.trim();
    }

    if (!folderPath) {
      return res.json({ success: false, message: '未选择文件夹' });
    }

    // 自动识别项目信息
    const projectInfo = await detectProjectInfo(folderPath);

    res.json({
      success: true,
      path: folderPath,
      detected: projectInfo
    });
  } catch (error) {
    res.status(500).json({ error: '选择文件夹失败', message: error.message });
  }
});

// 自动检测项目信息
async function detectProjectInfo(projectPath) {
  const info = {
    name: path.basename(projectPath),
    type: '',
    stack: [],
    description: '',
    port: null
  };

  try {
    // 检测项目类型和技术栈
    info.stack = await identifyTechStack(projectPath);

    // 读取 README 生成描述
    const readmeFiles = ['README.md', 'readme.md', 'README', 'README.txt'];
    for (const readme of readmeFiles) {
      const readmePath = path.join(projectPath, readme);
      if (fs.existsSync(readmePath)) {
        const content = fs.readFileSync(readmePath, 'utf8');
        // 提取第一段作为描述
        const lines = content.split('\n').filter(line => line.trim());
        info.description = lines.slice(0, 3).join(' ').substring(0, 200);
        break;
      }
    }

    // 尝试检测端口
    const packageJsonPath = path.join(projectPath, 'package.json');
    if (fs.existsSync(packageJsonPath)) {
      const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
      // 从 scripts 中查找端口信息
      const scripts = Object.values(packageJson.scripts || {}).join(' ');
      const portMatch = scripts.match(/PORT[=:\s]+(\d+)|port[=:\s]+(\d+)|--port[=\s]+(\d+)/i);
      if (portMatch) {
        info.port = parseInt(portMatch[1] || portMatch[2] || portMatch[3]);
      }
    }

  } catch (error) {
    console.error('检测项目信息失败:', error);
  }

  return info;
}

// 识别技术栈
async function identifyTechStack(projectPath) {
  const stack = new Set();

  // 检查文件存在性
  const files = {
    'package.json': false,
    'requirements.txt': false,
    'Cargo.toml': false,
    'go.mod': false,
    'pom.xml': false,
    'build.gradle': false,
    'Gemfile': false,
    'composer.json': false
  };

  for (const file of Object.keys(files)) {
    files[file] = fs.existsSync(path.join(projectPath, file));
  }

  // Node.js / JavaScript / TypeScript
  if (files['package.json']) {
    try {
      const packageJson = JSON.parse(
        fs.readFileSync(path.join(projectPath, 'package.json'), 'utf8')
      );
      const deps = { ...packageJson.dependencies, ...packageJson.devDependencies };

      // 框架检测
      if (deps.react || deps['@types/react']) stack.add('React');
      if (deps.vue || deps['@vue/cli-service']) stack.add('Vue');
      if (deps['@angular/core']) stack.add('Angular');
      if (deps.next) stack.add('Next.js');
      if (deps.nuxt) stack.add('Nuxt.js');
      if (deps.svelte) stack.add('Svelte');

      // 后端框架
      if (deps.express) stack.add('Express');
      if (deps.koa) stack.add('Koa');
      if (deps['@nestjs/core']) stack.add('NestJS');
      if (deps.fastify) stack.add('Fastify');

      // 构建工具
      if (deps.vite) stack.add('Vite');
      if (deps.webpack) stack.add('Webpack');

      // 其他
      if (deps.typescript || deps['@types/node']) stack.add('TypeScript');
      if (deps.electron) stack.add('Electron');
      if (deps['@tauri-apps/api']) stack.add('Tauri');

      // 如果没有检测到特定框架，标记为 Node.js
      if (stack.size === 0 || (stack.size === 1 && stack.has('TypeScript'))) {
        stack.add('Node.js');
      }
    } catch (error) {
      stack.add('Node.js');
    }
  }

  // Python
  if (files['requirements.txt']) {
    try {
      const requirements = fs.readFileSync(
        path.join(projectPath, 'requirements.txt'),
        'utf8'
      );

      if (requirements.includes('django')) stack.add('Django');
      if (requirements.includes('flask')) stack.add('Flask');
      if (requirements.includes('fastapi')) stack.add('FastAPI');
      if (requirements.includes('tornado')) stack.add('Tornado');

      if (stack.size === 0) {
        stack.add('Python');
      }
    } catch (error) {
      stack.add('Python');
    }
  }

  // Rust
  if (files['Cargo.toml']) {
    stack.add('Rust');
  }

  // Go
  if (files['go.mod']) {
    stack.add('Go');
  }

  // Java
  if (files['pom.xml']) {
    stack.add('Java');
    stack.add('Maven');
  }
  if (files['build.gradle']) {
    stack.add('Java');
    stack.add('Gradle');
  }

  // Ruby
  if (files['Gemfile']) {
    stack.add('Ruby');
    try {
      const gemfile = fs.readFileSync(path.join(projectPath, 'Gemfile'), 'utf8');
      if (gemfile.includes('rails')) stack.add('Rails');
    } catch (error) {
      // 忽略错误
    }
  }

  // PHP
  if (files['composer.json']) {
    stack.add('PHP');
    try {
      const composer = JSON.parse(
        fs.readFileSync(path.join(projectPath, 'composer.json'), 'utf8')
      );
      if (composer.require && composer.require['laravel/framework']) {
        stack.add('Laravel');
      }
    } catch (error) {
      // 忽略错误
    }
  }

  return Array.from(stack);
}

// ========== 数据导出 API ==========

// 导出项目配置到 JSON 格式
app.get('/api/projects/export', (req, res) => {
  try {
    const config = db.getProjectsForConfig();
    res.json(config);
  } catch (error) {
    res.status(500).json({ error: '导出配置失败', message: error.message });
  }
});

// 下载项目配置为 JSON 文件
app.get('/api/projects/export/download', (req, res) => {
  try {
    const config = db.getProjectsForConfig();
    const filename = `projects-backup-${new Date().toISOString().split('T')[0]}.json`;

    res.setHeader('Content-Type', 'application/json');
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
    res.send(JSON.stringify(config, null, 2));
  } catch (error) {
    res.status(500).json({ error: '下载配置失败', message: error.message });
  }
});

// 注册进程管理路由
registerProcessRoutes(app, PROJECT_ROOT, PROJECTS_CONFIG, fs);

// 注册项目管理路由（Todos, Milestones, Labels 等）
registerManagementRoutes(app);

// 注册 Todo AI 路由（任务拆分、协作、验证）
registerTodoAiRoutes(app);

// 注册项目分析路由
registerAnalysisRoutes(app, PROJECT_ROOT, PROJECTS_CONFIG);

// 注册文件管理路由
app.use('/api', fileRoutes);

// 启动服务器
app.listen(PORT, () => {
  console.log(`🚀 项目管理系统后端运行在 http://localhost:${PORT}`);
  console.log(`📁 项目根目录: ${PROJECT_ROOT}`);
  console.log(`📋 配置文件: ${PROJECTS_CONFIG}`);
  console.log(`💾 数据库: project-manager.db`);

  // 同步项目配置到数据库
  try {
    const config = JSON.parse(fs.readFileSync(PROJECTS_CONFIG, 'utf8'));
    db.syncProjectsFromConfig(config);
    console.log('✅ 项目配置已同步到数据库');
  } catch (error) {
    console.warn('⚠️  同步项目配置失败:', error.message);
  }
});

// 优雅关闭
process.on('SIGTERM', () => {
  console.log('收到 SIGTERM 信号，正在停止所有进程...');
  processManager.stopAll();
  process.exit(0);
});

process.on('SIGINT', () => {
  console.log('\n收到 SIGINT 信号，正在停止所有进程...');
  processManager.stopAll();
  process.exit(0);
});
